[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = '''
    geolocation=(self),
    microphone=()'''

    Strict-Transport-Security = '''
    max-age="63072000",
    includeSubDomains
    preload'''

    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
