[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = '''
      (unsafe-none|require-corp);
      report-to='default''''

    Permissions-Policy = '''
      geolocation=(self),
      microphone=()'''

    Referrer-Policy = "no-referrer-when-downgrade

    Strict-Transport-Security = '''
      max-age=63072000;
      includeSubDomains;
      preload'''

    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
